name: matlab

env:
  CTEST_NO_TESTS_ACTION: error
  MATLAB_RELEASE: R2023a

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"

# Engine can't start on CI runner Linux, but works on real Linux computer

jobs:

  linux:
    runs-on: ubuntu-latest

    env:
      CC: gcc-10
      CXX: g++-10
      FC: gfortran-10

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ env.MATLAB_RELEASE }}

    - uses: actions/checkout@v3

    - name: CMake workflow
      run: cmake -Bbuild -Dfortran=yes

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build -LE engine -V

  mac:
    runs-on: macos-latest

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ env.MATLAB_RELEASE }}

    - uses: actions/checkout@v3

    - name: CMake workflow
      run: cmake -Bbuild -Dfortran=no

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build -LE engine -V

  msvc:
    runs-on: windows-latest

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ env.MATLAB_RELEASE }}

    - uses: actions/checkout@v3

    - name: CMake workflow
      run: cmake -Bbuild -Dfortran=no

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build -C Release -LE engine -V
