name: matlab

env:
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"

# R2021a, R2021b: GCC 8
# R2022a, R2022b: GCC 10

# Engine can't start on CI runner Linux, but works on real Linux computer

jobs:

  linux:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        release: [R2022b]

    env:
      CC: gcc-10
      CXX: g++-10
      FC: gfortran-10

    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.release }}

    - uses: actions/checkout@v3

    - name: CMake workflow
      run: cmake -Bbuild -Dfortran=yes

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build -LE engine -V

  mac:
    timeout-minutes: 10
    runs-on: macos-latest

    strategy:
      matrix:
        release: [R2022b]

    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.release }}

    - uses: actions/checkout@v3

    - name: CMake workflow
      run: cmake -Bbuild -Dfortran=no

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build -LE engine -V

  msvc:
    timeout-minutes: 10
    runs-on: windows-latest

    strategy:
      matrix:
        release: [R2022b]

    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.release }}

    - uses: actions/checkout@v3

    - name: CMake workflow
      run: cmake -Bbuild -Dfortran=no

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build -C Release -LE engine -V
